### ISSUE TITLE
ingress-operator is not necessary

### ISSUE THREAD

**Issue by r7vme** [giantswarm/ingress-operator#96]
For TCP load-balancing that is done by ingress-operator, we don't actually need current complex implementation (with nginx-ingress-controller).

Instead we can expose TCP ports from `worker` service by defining `nodePort`.

```
  - name: http
    port: 30010
    protocol: TCP
    nodePort: 31060 # <== expose this port on host machines
    targetPort: 30010
  - name: https
    port: 30011
    protocol: TCP
    nodePort: 31061 # <== expose this port on host machines
    targetPort: 30011
```

We just need to specify `nodePort` taken from CR (right now random assigned by Kubernetes) in kvm-operator.

**Comment by corest** [comment]
There are warnings like this:

```
E0703 14:41:12.517502       1 repair.go:152] the port 30005 for service api-service/giantswarm is not within the port range 31000-32767; please recreate
E0703 14:41:12.517602       1 repair.go:152] the port 30405 for service cluster-service/giantswarm is not within the port range 31000-32767; please recreate
E0703 14:41:12.518658       1 repair.go:152] the port 30606 for service kubernetesd/giantswarm is not within the port range 31000-32767; please recreate
E0703 14:41:12.519787       1 repair.go:152] the port 30698 for service default-http-backend/kube-system is not within the port range 31000-32767; please recreate
E0703 14:41:12.522176       1 repair.go:152] the port 30010 for service nginx-ingress-controller/kube-system is not within the port range 31000-32767; please recreate
E0703 14:41:12.523263       1 repair.go:152] the port 30011 for service nginx-ingress-controller/kube-system is not within the port range 31000-32767; please recreate
E0703 14:44:12.539826       1 repair.go:152] the port 30005 for service api-service/giantswarm is not within the port range 31000-32767; please recreate
E0703 14:44:12.539879       1 repair.go:152] the port 30405 for service cluster-service/giantswarm is not within the port range 31000-32767; please recreate
E0703 14:44:12.541037       1 repair.go:152] the port 30606 for service kubernetesd/giantswarm is not within the port range 31000-32767; please recreate
E0703 14:44:12.542162       1 repair.go:152] the port 30698 for service default-http-backend/kube-system is not within the port range 31000-32767; please recreate
E0703 14:44:12.543324       1 repair.go:152] the port 30010 for service nginx-ingress-controller/kube-system is not within the port range 31000-32767; please recreate
E0703 14:44:12.544441       1 repair.go:152] the port 30011 for service nginx-ingress-controller/kube-system is not within the port range 31000-32767; please recreate
```

But services keep working

**Comment by xh3b4sd** [comment]
I like that you picked this up and started working on it. Can you please move the issues to WIP in the boards? 

I was wondering about the migration path and if there is anything to worry about for older clusters and their upcoming lifecycle. Does all this nicely integrate or do we have to consider extra steps? We should definitely check upgrades of KVM clusters and such. You know the dance. FYI I am working on e2e tests for updates right now. They are coming this or next week. KVM just has to provide the infra then with `gastropod` and stuff. <3

**Comment by r7vme** [comment]
>  Does all this nicely integrate or do we have to consider extra steps? 

For in-place upgrades we still need a migration path. I need to test this. I expect that nodePort will be assgned, because it's already occupied by other service (managed by ingress-operator). Dumb migration path, is just remove ingressconfig, but this can cause some downtime.

**Comment by r7vme** [comment]
All PRs were merged.

https://github.com/giantswarm/kvm-operator/pull/525
https://github.com/giantswarm/kubernetesd/pull/397

New kvm release 2.11.0 now exposes ingress w/o ingress-operator.

Upgraded clusters will continue to use "nginx" based proxying, because kvm-operator has compatibility mode for case, when no port mappings are specified. Later when we get rid of "old" clusters we can get rid of ingress-operator from our installations.

**Comment by xh3b4sd** [comment]
How can we track the removal of `ingress-operator`?

**Comment by r7vme** [comment]
Added internal issue to track https://github.com/giantswarm/giantswarm/issues/3952
